name: yaml_io
description: yaml_io package project
version: 2025.420.2340
homepage:
repository: https://github.com/dart-pkg/yaml_io

environment:
  sdk: ^3.7.2

dependencies:
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.15
  embed: ^1.4.1
  lints: ^5.1.1
  output: ^1.0.2
  test: ^1.25.15
