name: yaml_io
description: |-
  [yaml_io]
  A wrapper library for yaml/yaml_writer packages.
version: 2025.430.1710
homepage: 
repository: https://github.com/dart-pkg/yaml_io
topics:
  - yaml
  - config-format
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  web: 
  windows: 
dependencies:
  yaml: ^3.1.3
  yaml_magic: ^1.0.6
  yaml_writer: ^2.1.0
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.430.1731
  test: ^1.25.15
