name: yaml_io
description: |-
  [yaml_io]
  A wrapper library for yaml/yaml_writer packages.
version: 2025.426.511
homepage:
repository: https://github.com/dart-pkg/yaml_io

environment:
  sdk: ^3.7.2
dependencies:
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
dev_dependencies:
  lints: ^5.1.1
  output: ^1.0.7
  test: ^1.25.15


